// src/components/Shell.jsx
import { Link, useLocation } from 'react-router-dom';
import { supabase } from '../lib/supabase.js';

export default function Shell({ children }) {
  const location = useLocation();

  return (
    <div className="app-shell">
      <aside className="sidebar">
        <div className="brand">AQUILE ADMIN</div>
        <nav className="nav">
          <Link to="/" aria-current={location.pathname === '/'}>
            Articoli
          </Link>
          <Link to="/articles/new">Nuovo articolo</Link>
        </nav>
        <button
          type="button"
          className="button secondary"
          onClick={() => supabase.auth.signOut()}
        >
          Logout
        </button>
      </aside>
      <main className="content">{children}</main>
    </div>
  );
}

// src/app/layout/shell.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

import { AuthService } from '../core/auth.service';

@Component({
  selector: 'app-shell',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <div class="app-shell">
      <aside class="sidebar">
        <div class="brand">AQUILE ADMIN</div>

        <nav class="nav">
          <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">
            Articoli
          </a>
          <a routerLink="/articles/new" routerLinkActive="active">Nuovo articolo</a>
        </nav>

        <button type="button" class="button secondary" (click)="logout()">Logout</button>
      </aside>

      <main class="content">
        <router-outlet />
      </main>
    </div>
  `,
})
export class ShellComponent {
  constructor(private readonly authService: AuthService) {}

  logout(): void {
    void this.authService.signOut();
  }
}
